import {
    ApplicationConfig,
    DEFAULT_CURRENCY_CODE,
    inject,
    LOCALE_ID,
    provideZonelessChangeDetection,
    APP_INITIALIZER,
} from '@angular/core';
import {
    provideTranslateService,
    provideTranslateLoader,
} from '@ngx-translate/core';
import { provideTranslateHttpLoader } from '@ngx-translate/http-loader';
import { provideHttpClient } from '@angular/common/http';
import { applicationConfig, type Preview } from '@storybook/angular';
import { DatePipe } from '@angular/common';

import { ThemeService } from '@design-system/tokens';

import '@angular/common/locales/global/en';
import '@angular/common/locales/global/pt';
import '@angular/common/locales/global/es';

interface BrandItem {
    value: string;
    title: string;
}

// Attempt to load dynamic theme list if generated by Style Dictionary
let brandItems: BrandItem[] = [{ value: 'default', title: 'Default' }];
try {
    // @ts-ignore
    const brandList = require('../src/lib/design-system/tokens/themeList');
    if (brandList && brandList.items) {
        brandItems = [
            ...brandItems,
            ...brandList.items.filter((item: BrandItem) => item.value !== 'default'),
        ];
    }
} catch (e) {
    console.error(e);
    brandItems = [{ value: 'default', title: 'Default' }];
}

const preview: Preview = {
    globalTypes: {
        theme: {
            description: 'Global color mode',
            defaultValue: 'light',
            toolbar: {
                title: 'Mode',
                icon: 'circlehollow',
                items: [
                    { value: 'light', icon: 'circlehollow', title: 'Light Mode' },
                    { value: 'dark', icon: 'circle', title: 'Dark Mode' },
                ],
                dynamicTitle: true,
            },
        },
        brand: {
            description: 'Global brand theme',
            defaultValue: 'default',
            toolbar: {
                title: 'Brand',
                icon: 'paintbrush',
                items: brandItems,
                dynamicTitle: true,
            },
        },
        locale: {
            description: 'Internationalization locale',
            defaultValue: 'en-GB',
            toolbar: {
                title: 'Language',
                icon: 'globe',
                items: [
                    { value: 'en-GB', right: '🇬🇧', title: 'English' },
                    { value: 'pt-PT', right: '🇵🇹', title: 'Português' },
                    { value: 'es-ES', right: '🇪🇸', title: 'Español' },
                ],
                dynamicTitle: true,
            },
        },
        currency: {
            description: 'Currency for price displays',
            defaultValue: 'GBP',
            toolbar: {
                title: 'Currency',
                icon: 'credit',
                items: [
                    { value: 'GBP', right: '£', title: 'GBP' },
                    { value: 'EUR', right: '€', title: 'EUR' },
                ],
                dynamicTitle: true,
            },
        },
    },
    parameters: {
        options: {
            storySort: {
                order: ['Design System', ['Introduction', 'Foundations', '*'], '*'],
            },
        },
    },
    decorators: [
        applicationConfig({
            providers: [
                provideZonelessChangeDetection(),
                provideHttpClient(),
                {
                    provide: APP_INITIALIZER,
                    useFactory: () => {
                        const themeService = inject(ThemeService);
                        return () => themeService.initializeTokens();
                    },
                    multi: true,
                },
            ],
        }),
        (storyFn, context) => {
            const { theme, brand, currency } = context.globals;
            let { locale } = context.globals;
            locale = locale || 'en-GB';
            const html = document.documentElement;
            if (theme === 'dark') {
                html.classList.add('dark');
            } else {
                html.classList.remove('dark');
            }

            // Apply brand data attribute for Style Dictionary tokens
            html.setAttribute('data-theme', brand || 'default');

            // Set localization and currency data attributes
            html.setAttribute('lang', locale);
            html.setAttribute('data-currency', currency || 'GBP');

            const story = storyFn(context);

            return {
                ...story,
                moduleMetadata: {
                    ...(story.moduleMetadata || {}),
                    imports: [...(story.moduleMetadata?.imports || [])],
                    providers: [
                        ...(story.moduleMetadata?.providers || []),
                        { provide: DEFAULT_CURRENCY_CODE, useValue: currency },
                        DatePipe,
                        { provide: LOCALE_ID, useValue: locale },
                        provideTranslateService({
                            loader: provideTranslateHttpLoader({
                                prefix: '/assets/i18n/',
                                suffix: '.json',
                            }),
                            fallbackLang: locale,
                            lang: locale,
                        }),
                    ],
                },
            };
        },
    ],
};

export default preview;
