const fs = require('fs');
const path = require('path');

async function build() {
  const { default: StyleDictionary } = await import('style-dictionary');

  const sd = new StyleDictionary({
    source: ['tokens/properties/**/*.json'],
    platforms: {
      ts: {
        transformGroup: 'js',
        buildPath: 'tokens/src/lib/',
        files: [{
          destination: 'tokens.ts',
          format: 'typescript/multibrand'
        }]
      }
    }
  });

  sd.registerFormat({
    name: 'typescript/multibrand',
    format: async function ({ dictionary }) {
      // Group properties by top-level key
      const tokens = dictionary.tokens;
      const coreTokens = tokens.core;
      delete tokens.core;
      const brands = tokens;
      const brandTokens = {};
      Object.keys(brands).forEach(key => {
        let brand = brands[key];
        brandTokens[key] = minify(deepMerge(coreTokens, brand))
      });

      return `/** Generated by Antigravity */
export const coreTokens = ${JSON.stringify(coreTokens, null, 2)} as const;

export const brands = ${JSON.stringify(brandTokens, null, 2)} as const;

export type Brand = keyof typeof brands;

export const designTokens = {
  coreTokens,
  brands
} as const;

export type DesignTokens = typeof designTokens;
`;
    }
  });

  await sd.buildAllPlatforms();
}

/**
 * Perform a deep merge of objects.
 * Values from source will override values from target.
 *
 * @param {object} target - The base object
 * @param {object} source - The object with overriding values
 * @returns {object} - The merged object
 */
function deepMerge(target, source) {
  const result = { ...target };
  for (const key in source) {
    if (source[key] instanceof Object && !Array.isArray(source[key]) && target[key] instanceof Object) {
      result[key] = deepMerge(target[key], source[key]);
    } else {
      result[key] = source[key];
    }
  }
  return result;
}


function minify(obj) {
  if (obj.value !== undefined) {
    return obj.value;
  }
  const minified = {};
  for (const key in obj) {
    if (obj.hasOwnProperty(key)) {
      minified[key] = minify(obj[key]);
    }
  }
  return minified;
}

build().catch(console.error);

