/** Generated by Antigravity */
export const coreTokens = {
  "spacing": {
    "sm": {
      "value": "0.25rem",
      "filePath": "tokens/properties/core.json",
      "isSource": true,
      "original": {
        "value": "0.25rem"
      },
      "name": "CoreSpacingSm",
      "attributes": {
        "category": "core",
        "type": "spacing",
        "item": "sm"
      },
      "path": [
        "core",
        "spacing",
        "sm"
      ]
    },
    "md": {
      "value": "1.25rem",
      "filePath": "tokens/properties/core.json",
      "isSource": true,
      "original": {
        "value": "1.25rem"
      },
      "name": "CoreSpacingMd",
      "attributes": {
        "category": "core",
        "type": "spacing",
        "item": "md"
      },
      "path": [
        "core",
        "spacing",
        "md"
      ]
    },
    "lg": {
      "value": "1.5rem",
      "filePath": "tokens/properties/core.json",
      "isSource": true,
      "original": {
        "value": "1.5rem"
      },
      "name": "CoreSpacingLg",
      "attributes": {
        "category": "core",
        "type": "spacing",
        "item": "lg"
      },
      "path": [
        "core",
        "spacing",
        "lg"
      ]
    },
    "xl": {
      "value": "2rem",
      "filePath": "tokens/properties/core.json",
      "isSource": true,
      "original": {
        "value": "2rem"
      },
      "name": "CoreSpacingXl",
      "attributes": {
        "category": "core",
        "type": "spacing",
        "item": "xl"
      },
      "path": [
        "core",
        "spacing",
        "xl"
      ]
    },
    "2xl": {
      "value": "3rem",
      "filePath": "tokens/properties/core.json",
      "isSource": true,
      "original": {
        "value": "3rem"
      },
      "name": "CoreSpacing2xl",
      "attributes": {
        "category": "core",
        "type": "spacing",
        "item": "2xl"
      },
      "path": [
        "core",
        "spacing",
        "2xl"
      ]
    }
  },
  "font": {
    "family": {
      "heading": {
        "value": "Montserrat",
        "filePath": "tokens/properties/core.json",
        "isSource": true,
        "original": {
          "value": "Montserrat"
        },
        "name": "CoreFontFamilyHeading",
        "attributes": {
          "category": "core",
          "type": "font",
          "item": "family",
          "subitem": "heading"
        },
        "path": [
          "core",
          "font",
          "family",
          "heading"
        ]
      },
      "base": {
        "value": "Tahoma, Arial, 'Helvetica Neue', sans",
        "filePath": "tokens/properties/core.json",
        "isSource": true,
        "original": {
          "value": "Tahoma, Arial, 'Helvetica Neue', sans"
        },
        "name": "CoreFontFamilyBase",
        "attributes": {
          "category": "core",
          "type": "font",
          "item": "family",
          "subitem": "base"
        },
        "path": [
          "core",
          "font",
          "family",
          "base"
        ]
      }
    },
    "size": {
      "sm": {
        "value": "0.875rem",
        "filePath": "tokens/properties/core.json",
        "isSource": true,
        "original": {
          "value": "0.875rem"
        },
        "name": "CoreFontSizeSm",
        "attributes": {
          "category": "core",
          "type": "font",
          "item": "size",
          "subitem": "sm"
        },
        "path": [
          "core",
          "font",
          "size",
          "sm"
        ]
      },
      "md": {
        "value": "1rem",
        "filePath": "tokens/properties/core.json",
        "isSource": true,
        "original": {
          "value": "1rem"
        },
        "name": "CoreFontSizeMd",
        "attributes": {
          "category": "core",
          "type": "font",
          "item": "size",
          "subitem": "md"
        },
        "path": [
          "core",
          "font",
          "size",
          "md"
        ]
      },
      "lg": {
        "value": "1.125rem",
        "filePath": "tokens/properties/core.json",
        "isSource": true,
        "original": {
          "value": "1.125rem"
        },
        "name": "CoreFontSizeLg",
        "attributes": {
          "category": "core",
          "type": "font",
          "item": "size",
          "subitem": "lg"
        },
        "path": [
          "core",
          "font",
          "size",
          "lg"
        ]
      }
    },
    "weight": {
      "regular": {
        "value": "400",
        "filePath": "tokens/properties/core.json",
        "isSource": true,
        "original": {
          "value": "400"
        },
        "name": "CoreFontWeightRegular",
        "attributes": {
          "category": "core",
          "type": "font",
          "item": "weight",
          "subitem": "regular"
        },
        "path": [
          "core",
          "font",
          "weight",
          "regular"
        ]
      },
      "medium": {
        "value": "500",
        "filePath": "tokens/properties/core.json",
        "isSource": true,
        "original": {
          "value": "500"
        },
        "name": "CoreFontWeightMedium",
        "attributes": {
          "category": "core",
          "type": "font",
          "item": "weight",
          "subitem": "medium"
        },
        "path": [
          "core",
          "font",
          "weight",
          "medium"
        ]
      },
      "bold": {
        "value": "700",
        "filePath": "tokens/properties/core.json",
        "isSource": true,
        "original": {
          "value": "700"
        },
        "name": "CoreFontWeightBold",
        "attributes": {
          "category": "core",
          "type": "font",
          "item": "weight",
          "subitem": "bold"
        },
        "path": [
          "core",
          "font",
          "weight",
          "bold"
        ]
      }
    }
  },
  "radius": {
    "sm": {
      "value": "0.25rem",
      "filePath": "tokens/properties/core.json",
      "isSource": true,
      "original": {
        "value": "0.25rem"
      },
      "name": "CoreRadiusSm",
      "attributes": {
        "category": "core",
        "type": "radius",
        "item": "sm"
      },
      "path": [
        "core",
        "radius",
        "sm"
      ]
    },
    "md": {
      "value": "0.375rem",
      "filePath": "tokens/properties/core.json",
      "isSource": true,
      "original": {
        "value": "0.375rem"
      },
      "name": "CoreRadiusMd",
      "attributes": {
        "category": "core",
        "type": "radius",
        "item": "md"
      },
      "path": [
        "core",
        "radius",
        "md"
      ]
    },
    "lg": {
      "value": "0.5rem",
      "filePath": "tokens/properties/core.json",
      "isSource": true,
      "original": {
        "value": "0.5rem"
      },
      "name": "CoreRadiusLg",
      "attributes": {
        "category": "core",
        "type": "radius",
        "item": "lg"
      },
      "path": [
        "core",
        "radius",
        "lg"
      ]
    }
  }
} as const;

export const brands = {
  "default": {
    "spacing": {
      "sm": "0.25rem",
      "md": "1.25rem",
      "lg": "1.5rem",
      "xl": "2rem",
      "2xl": "3rem"
    },
    "font": {
      "family": {
        "heading": "Montserrat",
        "base": "\"Inter\", sans-serif"
      },
      "size": {
        "sm": "0.875rem",
        "md": "1rem",
        "lg": "1.125rem"
      },
      "weight": {
        "regular": "400",
        "medium": "500",
        "bold": "700"
      }
    },
    "radius": {
      "sm": "0.25rem",
      "md": "0.375rem",
      "lg": "0.5rem"
    },
    "asset": {
      "icon": {
        "logo": "assets/icons/logo.svg"
      },
      "font": {
        "Roboto": {
          "400": {
            "normal": "assets/fonts/Roboto-Regular",
            "italic": "assets/fonts/Roboto-Regular"
          },
          "700": {
            "normal": "assets/fonts/Roboto-Regular",
            "italic": "assets/fonts/Roboto-Regular"
          }
        }
      }
    },
    "color": {
      "primary": "#0F172A",
      "onPrimary": "#FFFFFF",
      "secondary": "#F1F5F9",
      "onSecondary": "#0F172A",
      "surface": "#FFFFFF",
      "error": "#EF4444",
      "success": "#10B981",
      "outline": "#CBD5E1"
    }
  },
  "partner": {
    "spacing": {
      "sm": "0.25rem",
      "md": "1.25rem",
      "lg": "1.5rem",
      "xl": "2rem",
      "2xl": "3rem"
    },
    "font": {
      "family": {
        "heading": "Montserrat",
        "base": "\"Poppins\", sans-serif"
      },
      "size": {
        "sm": "0.875rem",
        "md": "1rem",
        "lg": "1.125rem"
      },
      "weight": {
        "regular": "400",
        "medium": "500",
        "bold": "700"
      }
    },
    "radius": {
      "sm": "0.25rem",
      "md": "0.375rem",
      "lg": "0.5rem"
    },
    "color": {
      "primary": "#4338CA",
      "onPrimary": "#FFFFFF",
      "secondary": "#E0E7FF",
      "onSecondary": "#4338CA",
      "surface": "#FFFFFF",
      "error": "#DC2626",
      "success": "#059669",
      "outline": "#94A3B8"
    }
  }
} as const;

export type Brand = keyof typeof brands;

export const designTokens = {
  coreTokens,
  brands
} as const;

export type DesignTokens = typeof designTokens;
